CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/src/{{ cookiecutter.module_name }}/common/spark.py

Remove unused enable glue setting
This let the templated code crash when you ran it

Remove the unused enable_glue setting

---

CHANGELOG.md
DEVELOPMENT.md

Updating the dev docs to be up to date
They were not up to date
Not needed

Update the development docs and fix the changelog

---

CHANGELOG.md
project/python/{{ cookiecutter.project_name }}/src/{{ cookiecutter.module_name }}/app.py

Configure the logging framework in the python template

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Upgrade the spark images
Previous spark images contained 2 versions of the aws sdk
Running the new spark images

Upgrade to latest spark 2.4.3 dataminded image

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/python/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
resource/aws/container-iam-role-s3/{{ cookiecutter.resource_name }}/{{ cookiecutter.resource_name }}.tf

Make sure the generated service account are kubernetes compliant
Othewise an apply can fail
None

Make sure the generated service account are kubernetes compliant

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/spark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py

Add support for datafy instance types

Add support for datafy instance types

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/Makefile
project/dbt/{{ cookiecutter.project_name }}/README.md

Added a makefile to the dbt template to make it a bit easier for users to use the dbt command line
You need to specify the profiles-dir, and project-dir flag to dbt which is hard to figure out as a user
Rendering the template and testing the makefile

Added a makefile to the dbt template

---

CHANGELOG.md

Update CHANGELOG.md for 0.5.0

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/spark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py

From 0.39.0 image field won't be required anymore

Remove the image field from the templates

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/pyspark/{{ cookiecutter.project_name }}/Pipfile
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements-3.txt
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements.in
project/spark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/build.gradle

Upgrade to spark 3.0.2
It got released, to keep up to date
Tested the image on another project

Update to spark 3.0.2

---

CHANGELOG.md

Update CHANGELOG.md to 0.6.0

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/pyspark/{{ cookiecutter.project_name }}/Pipfile
project/pyspark/{{ cookiecutter.project_name }}/Pipfile-3.0.lock
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements-3.txt
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements.in
project/spark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/build.gradle

Upgrading to spark 3.1.1
It got released
The image was tested on another repo

Upgrade templates to spark 3.1.1

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/spark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py

Change the import paths to be 0.42.0 compliant.

Change the operator import paths for datafy 0.42.0

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/spark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py

Added datafy path to macros

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py

Remove name parameter from DatafyContainerOperator
This is not required anymore

Remove name from DatafyContainerOperator

---

CHANGELOG.md
project/dbt/cookiecutter.json
project/dbt/hooks/post_gen_project.py
project/dbt/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/dbt/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/pyspark/cookiecutter.json
project/pyspark/hooks/post_gen_project.py
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/resources/variables.tf
project/pyspark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/python/cookiecutter.json
project/python/hooks/post_gen_project.py
project/python/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/python/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/spark/cookiecutter.json
project/spark/hooks/post_gen_project.py
project/spark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/spark/{{ cookiecutter.project_name }}/resources/variables.tf
project/spark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
resource/aws/container-iam-role-s3/cookiecutter.json
resource/aws/container-iam-role-s3/{{ cookiecutter.resource_name }}/{{ cookiecutter.resource_name }}.tf
tests/projects/test_dbt.py
tests/projects/test_pyspark.py
tests/projects/test_python.py
tests/projects/test_spark.py

Also make sure every project has a datafy managed
role option.

Migrate to datafy operator V2

---

CHANGELOG.md
project/spark/{{ cookiecutter.project_name }}/build.gradle
project/spark/{{ cookiecutter.project_name }}/gradle/wrapper/gradle-wrapper.properties
project/spark/{{ cookiecutter.project_name }}/gradlew
project/spark/{{ cookiecutter.project_name }}/gradlew.bat

Upgrade to gradle 7.0.2

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/pyspark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/python/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/spark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf

Underscores in project names will be replaced with dots

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/pyspark/{{ cookiecutter.project_name }}/Pipfile
project/pyspark/{{ cookiecutter.project_name }}/Pipfile-3.0.lock
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements-3.txt
project/pyspark/{{ cookiecutter.project_name }}/dev-requirements.in
project/spark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/build.gradle

Upgrade spark version to 3.1.2

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Upgrade spark images to v2

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/pyspark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/python/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/spark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf

Upgrade to hadoop 3.3.1 plus fix assume role policies

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Upgrade the image for spark to latest

---

CHANGELOG.md
project/pyspark/cookiecutter.json
project/pyspark/hooks/post_gen_project.py
project/pyspark/hooks/pre_gen_project.py
project/pyspark/{{ cookiecutter.project_name }}/.python-version
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/pyspark/{{ cookiecutter.project_name }}/README.md
project/pyspark/{{ cookiecutter.project_name }}/dags/{{ cookiecutter.project_name }}.py
project/pyspark/{{ cookiecutter.project_name }}/setup.py
project/pyspark/{{ cookiecutter.project_name }}/src/{{ cookiecutter.module_name }}/streaming_app.py
project/pyspark/{{ cookiecutter.project_name }}/streaming.yaml
project/spark/{{ cookiecutter.project_name }}/Dockerfile
tests/projects/test_pyspark.py

Support for pyspark streaming will be added to datafy in a next release

Added spark streaming to the pyspark project

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/streaming.yaml

Fixed an issue in the `streaming.yaml` file of the pyspark template where the project name instead of the module name was used.

Fix small issue with pyspark streaming

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Use the scala spark 2.13 image

---

CHANGELOG.md
resource/aws/container-iam-role-s3/{{ cookiecutter.resource_name }}/{{ cookiecutter.resource_name }}.tf

Use like expression for default resources template.

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Update spark images to include patch for cve-2021-4104

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/Dockerfile
project/spark/{{ cookiecutter.project_name }}/Dockerfile

Update spark images to include patch for setuptools in debian.

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/pyspark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/python/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
project/spark/{{ cookiecutter.project_name }}/resources/{{ cookiecutter.project_name }}.tf
resource/aws/container-iam-role-s3/{{ cookiecutter.resource_name }}/{{ cookiecutter.resource_name }}.tf
resource/aws/spark-iam-role-glue/cookiecutter.json
resource/aws/spark-iam-role-glue/{{ cookiecutter.resource_name }}/{{ cookiecutter.resource_name }}.tf

Use the exact uuid pattern matching
Makes it sure only the relevant project can assume the role

Use strict uuid pattern matching

---

project/pyspark/{{ cookiecutter.project_name }}/src/{{ cookiecutter.module_name }}/app.py

Fix main method pyspark

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/dbt/{{ cookiecutter.project_name }}/.gitpod.yml
project/pyspark/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/pyspark/{{ cookiecutter.project_name }}/.gitpod.yml
project/python/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/python/{{ cookiecutter.project_name }}/.gitpod.yml
project/spark/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/spark/{{ cookiecutter.project_name }}/.gitpod.yml

Make AWS generally available in dockerfile as any other command instead of in a special folder.

Move aws install to dockerfile and install in /usr/local/bin

---

CHANGELOG.md

Added pyspark 2.x removal to the changelog

---

CHANGELOG.md
dev-requirements.txt
project/dbt/cookiecutter.json
project/dbt/{{ cookiecutter.project_name }}/.devcontainer/Dockerfile
project/dbt/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/dbt/{{ cookiecutter.project_name }}/Dockerfile
project/dbt/{{ cookiecutter.project_name }}/Makefile
requirements.in
requirements.txt

Upgrade to dbt v1.3.2
On a local sample project, and the unit tests

Upgrade DBT support to v1.3.2

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/Dockerfile

Adding `dbt ls` in the image to enable caching
On projects with many models, parsing all the files takes significant time. By making sure the cache is added to the image this time is reduced
Running locally

Improve dbt startup latency by adding caching

---

CHANGELOG.md

Prepare release 1.3.2

---

CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/.devcontainer/devcontainer.json
project/dbt/{{ cookiecutter.project_name }}/.gitpod.yml
project/pyspark/{{ cookiecutter.project_name }}/.devcontainer/devcontainer.json
project/pyspark/{{ cookiecutter.project_name }}/.gitpod.yml
project/python/{{ cookiecutter.project_name }}/.devcontainer/devcontainer.json
project/python/{{ cookiecutter.project_name }}/.gitpod.yml
project/spark/{{ cookiecutter.project_name }}/.devcontainer/devcontainer.json
project/spark/{{ cookiecutter.project_name }}/.gitpod.yml

use static website url instead of public s3 bucket
use of public s3 bucket is being phased out

Use static.conveyordata.com instead of public s3 bucket

---

CHANGELOG.md
dev-requirements.txt
requirements.txt

By removing the requirements.txt and regenerating it a lot of packages are upgraded to the latest version

Regen dependencies

---

project/dbt/{{ cookiecutter.project_name }}/Makefile

Forgot to upgrade the version in the makefile

Increase version in dbt makefile to 1.6.0

---

.github/workflows/test.yml
CHANGELOG.md
project/dbt/{{ cookiecutter.project_name }}/resources/variables.tf
project/pyspark/{{ cookiecutter.project_name }}/resources/variables.tf
project/python/{{ cookiecutter.project_name }}/resources/variables.tf
project/spark/{{ cookiecutter.project_name }}/resources/variables.tf
resource/aws/container-iam-role-s3/{{ cookiecutter.resource_name }}/variables.tf
resource/aws/dbt-iam-role-s3/{{ cookiecutter.resource_name }}/variables.tf
resource/aws/spark-iam-role-glue/{{ cookiecutter.resource_name }}/variables.tf

Remove unused variables
These variables should not be used anymore
/

Remove variable as it is not supported anymore.

---

CHANGELOG.md
project/pyspark/{{ cookiecutter.project_name }}/src/{{ cookiecutter.module_name }}/common/spark.py
project/spark/{{ cookiecutter.project_name }}/src/main/scala/{{ cookiecutter.module_name }}/common/SparkSessions.scala

remove unnecessary config
not needed anymore
/

Remove unnecessary config as it is fixed in Spark now.

---

CHANGELOG.md

Prepare release 1.4.1

---

.flake8
.github/workflows/release.yml
.github/workflows/test.yml
dev-requirements.in
dev-requirements.txt
project/dbt/hooks/post_gen_project.py
project/python/hooks/post_gen_project.py
tests/projects/test_dbt.py
tests/projects/test_pyspark.py
tests/projects/test_python.py
tests/projects/test_spark.py
tests/test_templates_manifest.py

Fix release flow

---

CHANGELOG.md
dev-requirements.txt
project/dbt/{{ cookiecutter.project_name }}/.devcontainer/Dockerfile
project/dbt/{{ cookiecutter.project_name }}/.gitpod.dockerfile
project/dbt/{{ cookiecutter.project_name }}/Dockerfile
requirements.in
requirements.txt

Upgrade to 1.8.3
New release
Tested by running the dbt container

Upgrade to dbt 1.8.3

---

CHANGELOG.md
project/python/{{ cookiecutter.project_name }}/dev-requirements.txt
project/python/{{ cookiecutter.project_name }}/requirements.txt

Upgrade libraries with security issues
Security issues
Installing and testing the project

Upgrade requests and urllib3

---

package/alert/{{ cookiecutter.package_name }}/README.md

The version will now be automatically resolved and downloaded hence specifying dependencies manually is not supported anymore
Update was not needed since it wasn't released yet
Remove unneeded docs

Cleanup readme after automating package dag validation

---

CHANGELOG.md

Prepare release 1.7.0

---

CODEOWNERS

Added code owners

---

CHANGELOG.md
dev-requirements.txt
project/python/{{ cookiecutter.project_name }}/dev-requirements.txt
project/python/{{ cookiecutter.project_name }}/requirements.txt
requirements.txt

cryptography and certifi had vulnerabilities

Upgrade dependencies for cryptography and certifi
